name: "CI and deployment"
on: [push]
jobs:
  ci-and-release:
    name: "CI and release"
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      USERNAME: ${{ github.actor }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
      - run: nix build .#container && ./result | docker load
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ github.token }}
      - run: docker tag $( docker image ls --format '{{.ID}}') ${{ FULL_IMAGE }}/$(docker image ls --format '{{.Tag}}')
      - run: docker push ${{ FULL_IMAGE }}/$(docker image ls --format '{{.Tag}}')
